package com.artempact.backend.artempact.repository.repository.card.creativeSeeksCollaboration.junction;

import com.artempact.backend.artempact.entity.card.creativeSeeksCollaboration.junction.CreativeSeeksCollaborationLocation;
import com.artempact.backend.artempact.repository.genericRepositoryNoJPA.GenericLocationRepository;

public interface CreativeSeeksCollaborationLocationRepository extends GenericLocationRepository<CreativeSeeksCollaborationLocation, Long> {
}
